double d = 5.55;
char c = '!';
bool b = true;
System.Console.WriteLine(d);
System.Console.WriteLine(c);
System.Console.WriteLine(b);
int i1 = 5;
int i2 = 9;
int sum = i1 + i2;
System.Console.WriteLine(sum);
long l1 = 8;
long sum2 = l1 + i1;
System.Console.WriteLine(sum2);
double d1 = 7.8;
double sum3 = d1 + i1;
System.Console.WriteLine(sum3);
int product1 = i1 * i2;
long product2 = l1 * i1;
double product3 = i1 * d1;
System.Console.WriteLine(product1);
System.Console.WriteLine(product2);
System.Console.WriteLine(product3);
int quotient = i1 / i2;
System.Console.WriteLine(quotient);
d1 = 7;
double quotient2 = i1 / d1;
System.Console.WriteLine(quotient2);